"""
Offline tests for ShopClient charge operations using stubsmith.replay().

The bundle contains two stubs for POST /api/payments/charges, distinguished by
fingerprint (body key structure):

  fingerprint 79148562d5fb5ae8  - request includes idempotency_key
    → always 201 (succeeded)
  fingerprint 4a17ca4d93dddd7d  - request omits idempotency_key
    → always 402 (card declined)

This fingerprint split is a natural consequence of how Stubsmith fingerprints
work: adding or removing any top-level key changes the structural hash.  In
the captured bundle both fingerprints have count: 2; _select_variant picks
the sole variant for each fingerprint (201 or 402 respectively).

Tests that need the success response pass idempotency_key; tests that need the
decline response omit it.  No inline bundle dict is required here because the
two paths have distinct fingerprints.
"""
import pytest

import stubsmith
from shopclient import CardDeclined, ShopClient

BASE_URL = "http://localhost:8081"

_SAMPLE_CARD = {
    "number": "4242424242424242",
    "exp_month": 5,
    "exp_year": 2028,
    "cvc": "359",
    "holder": "Test User",
}
_SAMPLE_CUSTOMER = {
    "email": "test@example.invalid",
    "name": "Test User",
    "phone": "+1 555 0000",
}


# ---------------------------------------------------------------------------
# POST /api/payments/charges - 201 (with idempotency_key)
# ---------------------------------------------------------------------------


def test_charge_success_returns_recorded_shape():
    """Client parses the 201 response from the bundle correctly.

    Passes idempotency_key so the fingerprint matches stub 79148562d5fb5ae8
    (the 201 variant in the bundle).
    """
    with stubsmith.replay():
        result = ShopClient(BASE_URL, "test-key").create_charge(
            amount_cents=4250,
            currency="EUR",
            card=_SAMPLE_CARD,
            customer=_SAMPLE_CUSTOMER,
            idempotency_key="test-idem-0001",
        )

    assert "charge_id" in result
    assert result["status"] == "succeeded"
    assert "amount_cents" in result
    assert result["currency"] == "EUR"
    # card.last4 and card.brand are kept (non-sensitive summary fields).
    assert result["card"]["last4"] == "4242"
    assert result["card"]["brand"] == "visa"


def test_charge_success_response_has_nested_card():
    """The 201 response body includes a nested card object with last4 and brand."""
    with stubsmith.replay():
        result = ShopClient(BASE_URL, "test-key").create_charge(
            amount_cents=4250,
            currency="EUR",
            card=_SAMPLE_CARD,
            customer=_SAMPLE_CUSTOMER,
            idempotency_key="test-idem-0002",
        )

    card = result.get("card", {})
    assert "last4" in card
    assert "brand" in card
    assert len(str(card["last4"])) == 4


# ---------------------------------------------------------------------------
# POST /api/payments/charges - 402 (no idempotency_key)
# ---------------------------------------------------------------------------


def test_charge_declined_raises_card_declined():
    """Omitting idempotency_key routes to fingerprint 4a17ca4d93dddd7d (402 stub).

    replay() serves the 402 response; ShopClient raises CardDeclined.
    """
    with stubsmith.replay():
        with pytest.raises(CardDeclined) as exc_info:
            ShopClient(BASE_URL, "test-key").create_charge(
                amount_cents=950_000,
                currency="USD",
                card=_SAMPLE_CARD,
                customer=_SAMPLE_CUSTOMER,
                # no idempotency_key → different fingerprint → 402 stub
            )

    assert exc_info.value.status == 402


def test_charge_declined_carries_charge_id_and_code():
    """CardDeclined exposes charge_id and code from the recorded response body."""
    with stubsmith.replay():
        with pytest.raises(CardDeclined) as exc_info:
            ShopClient(BASE_URL, "test-key").create_charge(
                amount_cents=950_000,
                currency="USD",
                card=_SAMPLE_CARD,
                customer=_SAMPLE_CUSTOMER,
            )

    err = exc_info.value
    # The charge_id is generated by the server (ch_<seq>) and varies between
    # runs; assert the prefix rather than a fabricated literal value.
    assert isinstance(err.charge_id, str) and err.charge_id.startswith("ch_")
    assert err.code == "INSUFFICIENT_FUNDS"
